FROM nginx:latest


COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY packages/core-vue3-vite/dist /usr/share/nginx/html
COPY packages/vue2/dist /usr/share/nginx/html
COPY packages/vue3/dist /usr/share/nginx/html
COPY packages/vue3-vite/dist /usr/share/nginx/html
COPY packages/react-umi/dist /usr/share/nginx/html
EXPOSE 80
